'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { PlaceOrderDialog } from '@/components/place-order-dialog';
import useSWR from 'swr';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

interface Signal {
  id: string;
  symbol: string;
  signal_type: 'buy' | 'sell';
  price: number;
  signal_strength: number;
  timestamp: string;
  status: string;
  strategy_id: string;
}

export default function SignalsPage() {
  const [filter, setFilter] = useState<'all' | 'buy' | 'sell'>('all');
  const { data, isLoading } = useSWR('/api/signals', fetcher, { refreshInterval: 10000 });

  const signals: Signal[] = data?.data || [];
  const filtered = signals.filter((s) => filter === 'all' || s.signal_type === filter);

  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp);
    return date.toLocaleString();
  };

  return (
    <main className="flex-1 p-6">
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold">Trading Signals</h1>
          <p className="text-muted-foreground mt-1">All signals generated by your strategies</p>
        </div>

        <Card className="bg-card border-border">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Active Signals</CardTitle>
              <CardDescription>Real-time trading signals</CardDescription>
            </div>
            <div className="flex gap-2">
              {(['all', 'buy', 'sell'] as const).map((f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={`px-4 py-2 rounded-md text-sm font-medium transition ${
                    filter === f
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-secondary text-foreground hover:bg-secondary/80'
                  }`}
                >
                  {f.charAt(0).toUpperCase() + f.slice(1)}
                </button>
              ))}
            </div>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="text-center py-12 text-muted-foreground">Loading signals...</div>
            ) : filtered.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                {signals.length === 0 ? 'No signals generated yet' : 'No signals match your filter'}
              </div>
            ) : (
              <div className="space-y-3">
                {filtered.map((signal) => (
                  <div
                    key={signal.id}
                    className="p-4 rounded-lg border border-border bg-secondary/30 hover:bg-secondary/50 transition"
                  >
                    <div className="grid grid-cols-1 md:grid-cols-7 gap-4 items-center">
                      <div>
                        <span className="text-2xl font-bold">{signal.symbol}</span>
                      </div>
                      <div>
                        <span className="text-xs text-muted-foreground">Price</span>
                        <p className="font-semibold">₹{signal.price.toFixed(2)}</p>
                      </div>
                      <div>
                        <span className="text-xs text-muted-foreground">Type</span>
                        <Badge variant={signal.signal_type === 'buy' ? 'default' : 'destructive'}>
                          {signal.signal_type.toUpperCase()}
                        </Badge>
                      </div>
                      <div>
                        <span className="text-xs text-muted-foreground">Strength</span>
                        <p className="font-semibold">{(signal.signal_strength * 100).toFixed(0)}%</p>
                      </div>
                      <div>
                        <span className="text-xs text-muted-foreground">Status</span>
                        <Badge variant="outline">{signal.status}</Badge>
                      </div>
                      <div>
                        <span className="text-xs text-muted-foreground">Generated</span>
                        <p className="font-semibold text-sm">{formatTime(signal.timestamp)}</p>
                      </div>
                      <div className="text-right">
                        <PlaceOrderDialog
                          symbol={signal.symbol}
                          currentPrice={signal.price}
                          signalType={signal.signal_type}
                          signalId={signal.id}
                          strategyId={signal.strategy_id}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
