'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import useSWR from 'swr';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

interface Signal {
  id: string;
  symbol: string;
  signal_type: 'buy' | 'sell';
  price: number;
  signal_strength: number;
  timestamp: string;
  status: string;
}

export default function SignalsList() {
  const { data, isLoading, error } = useSWR('/api/signals', fetcher, {
    refreshInterval: 10000,
  });

  const signals = data?.data || [];

  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const minutes = Math.floor(diff / 60000);

    if (minutes < 1) return 'just now';
    if (minutes < 60) return `${minutes}m ago`;
    if (minutes < 1440) return `${Math.floor(minutes / 60)}h ago`;
    return date.toLocaleDateString();
  };

  return (
    <Card className="bg-card border-border">
      <CardHeader>
        <CardTitle>Active Signals</CardTitle>
        <CardDescription>Latest trading signals generated by your strategies</CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="text-center py-8 text-muted-foreground">Loading signals...</div>
        ) : signals.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">No active signals yet</div>
        ) : (
          <div className="space-y-3">
            {signals.slice(0, 10).map((signal: Signal) => (
              <div
                key={signal.id}
                className="flex items-center justify-between p-4 rounded-lg bg-secondary/30 border border-border hover:bg-secondary/50 transition"
              >
                <div className="flex items-center gap-4">
                  <div className="flex flex-col">
                    <span className="font-semibold">{signal.symbol}</span>
                    <span className="text-sm text-muted-foreground">₹{signal.price.toFixed(2)}</span>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <Badge variant={signal.signal_type === 'buy' ? 'default' : 'destructive'}>
                    {signal.signal_type.toUpperCase()}
                  </Badge>
                  <div className="text-right">
                    <div className="text-sm font-medium">
                      {(signal.signal_strength * 100).toFixed(0)}% strength
                    </div>
                    <div className="text-xs text-muted-foreground">{formatTime(signal.timestamp)}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
